/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubernetes-sigs/federation-v2/pkg/apis/scheduling/v1alpha1"
	scheme "github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// JobSchedulingPreferencesGetter has a method to return a JobSchedulingPreferenceInterface.
// A group's client should implement this interface.
type JobSchedulingPreferencesGetter interface {
	JobSchedulingPreferences(namespace string) JobSchedulingPreferenceInterface
}

// JobSchedulingPreferenceInterface has methods to work with JobSchedulingPreference resources.
type JobSchedulingPreferenceInterface interface {
	Create(*v1alpha1.JobSchedulingPreference) (*v1alpha1.JobSchedulingPreference, error)
	Update(*v1alpha1.JobSchedulingPreference) (*v1alpha1.JobSchedulingPreference, error)
	UpdateStatus(*v1alpha1.JobSchedulingPreference) (*v1alpha1.JobSchedulingPreference, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.JobSchedulingPreference, error)
	List(opts v1.ListOptions) (*v1alpha1.JobSchedulingPreferenceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.JobSchedulingPreference, err error)
	JobSchedulingPreferenceExpansion
}

// jobSchedulingPreferences implements JobSchedulingPreferenceInterface
type jobSchedulingPreferences struct {
	client rest.Interface
	ns     string
}

// newJobSchedulingPreferences returns a JobSchedulingPreferences
func newJobSchedulingPreferences(c *SchedulingV1alpha1Client, namespace string) *jobSchedulingPreferences {
	return &jobSchedulingPreferences{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the jobSchedulingPreference, and returns the corresponding jobSchedulingPreference object, and an error if there is any.
func (c *jobSchedulingPreferences) Get(name string, options v1.GetOptions) (result *v1alpha1.JobSchedulingPreference, err error) {
	result = &v1alpha1.JobSchedulingPreference{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jobschedulingpreferences").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of JobSchedulingPreferences that match those selectors.
func (c *jobSchedulingPreferences) List(opts v1.ListOptions) (result *v1alpha1.JobSchedulingPreferenceList, err error) {
	result = &v1alpha1.JobSchedulingPreferenceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jobschedulingpreferences").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested jobSchedulingPreferences.
func (c *jobSchedulingPreferences) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("jobschedulingpreferences").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a jobSchedulingPreference and creates it.  Returns the server's representation of the jobSchedulingPreference, and an error, if there is any.
func (c *jobSchedulingPreferences) Create(jobSchedulingPreference *v1alpha1.JobSchedulingPreference) (result *v1alpha1.JobSchedulingPreference, err error) {
	result = &v1alpha1.JobSchedulingPreference{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("jobschedulingpreferences").
		Body(jobSchedulingPreference).
		Do().
		Into(result)
	return
}

// Update takes the representation of a jobSchedulingPreference and updates it. Returns the server's representation of the jobSchedulingPreference, and an error, if there is any.
func (c *jobSchedulingPreferences) Update(jobSchedulingPreference *v1alpha1.JobSchedulingPreference) (result *v1alpha1.JobSchedulingPreference, err error) {
	result = &v1alpha1.JobSchedulingPreference{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jobschedulingpreferences").
		Name(jobSchedulingPreference.Name).
		Body(jobSchedulingPreference).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *jobSchedulingPreferences) UpdateStatus(jobSchedulingPreference *v1alpha1.JobSchedulingPreference) (result *v1alpha1.JobSchedulingPreference, err error) {
	result = &v1alpha1.JobSchedulingPreference{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jobschedulingpreferences").
		Name(jobSchedulingPreference.Name).
		SubResource("status").
		Body(jobSchedulingPreference).
		Do().
		Into(result)
	return
}

// Delete takes name of the jobSchedulingPreference and deletes it. Returns an error if one occurs.
func (c *jobSchedulingPreferences) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jobschedulingpreferences").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *jobSchedulingPreferences) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jobschedulingpreferences").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched jobSchedulingPreference.
func (c *jobSchedulingPreferences) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.JobSchedulingPreference, err error) {
	result = &v1alpha1.JobSchedulingPreference{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("jobschedulingpreferences").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
