/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package internalversion

import (
	federation "github.com/kubernetes-sigs/federation-v2/pkg/apis/federation"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FederatedJobOverrideLister helps list FederatedJobOverrides.
type FederatedJobOverrideLister interface {
	// List lists all FederatedJobOverrides in the indexer.
	List(selector labels.Selector) (ret []*federation.FederatedJobOverride, err error)
	// FederatedJobOverrides returns an object that can list and get FederatedJobOverrides.
	FederatedJobOverrides(namespace string) FederatedJobOverrideNamespaceLister
	FederatedJobOverrideListerExpansion
}

// federatedJobOverrideLister implements the FederatedJobOverrideLister interface.
type federatedJobOverrideLister struct {
	indexer cache.Indexer
}

// NewFederatedJobOverrideLister returns a new FederatedJobOverrideLister.
func NewFederatedJobOverrideLister(indexer cache.Indexer) FederatedJobOverrideLister {
	return &federatedJobOverrideLister{indexer: indexer}
}

// List lists all FederatedJobOverrides in the indexer.
func (s *federatedJobOverrideLister) List(selector labels.Selector) (ret []*federation.FederatedJobOverride, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*federation.FederatedJobOverride))
	})
	return ret, err
}

// FederatedJobOverrides returns an object that can list and get FederatedJobOverrides.
func (s *federatedJobOverrideLister) FederatedJobOverrides(namespace string) FederatedJobOverrideNamespaceLister {
	return federatedJobOverrideNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// FederatedJobOverrideNamespaceLister helps list and get FederatedJobOverrides.
type FederatedJobOverrideNamespaceLister interface {
	// List lists all FederatedJobOverrides in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*federation.FederatedJobOverride, err error)
	// Get retrieves the FederatedJobOverride from the indexer for a given namespace and name.
	Get(name string) (*federation.FederatedJobOverride, error)
	FederatedJobOverrideNamespaceListerExpansion
}

// federatedJobOverrideNamespaceLister implements the FederatedJobOverrideNamespaceLister
// interface.
type federatedJobOverrideNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all FederatedJobOverrides in the indexer for a given namespace.
func (s federatedJobOverrideNamespaceLister) List(selector labels.Selector) (ret []*federation.FederatedJobOverride, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*federation.FederatedJobOverride))
	})
	return ret, err
}

// Get retrieves the FederatedJobOverride from the indexer for a given namespace and name.
func (s federatedJobOverrideNamespaceLister) Get(name string) (*federation.FederatedJobOverride, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(federation.Resource("federatedjoboverride"), name)
	}
	return obj.(*federation.FederatedJobOverride), nil
}
