apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: jobs.batch
spec:
  target:
    version: v1
    kind: Job
  namespaced: true
  comparisonField: Generation
  propagationEnabled: true
  template:
    group: core.federation.k8s.io
    version: v1alpha1
    kind: FederatedJob
  placement:
    kind: FederatedJobPlacement
  override:
    kind: FederatedJobOverride
  overridePath:
    - spec
    - parallelism
