apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: services
spec:
  target:
    version: v1
    kind: Service
  namespaced: true
  comparisonField: Generation
  propagationEnabled: true
  template:
    group: core.federation.k8s.io
    version: v1alpha1
    kind: FederatedService
  placement:
    kind: FederatedServicePlacement
