/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package federatedscheduling

import (
	"fmt"
	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	"k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/endpoints/request"
	"k8s.io/apiserver/pkg/registry/rest"
)

var (
	InternalReplicaSchedulingPreference = builders.NewInternalResource(
		"replicaschedulingpreferences",
		"ReplicaSchedulingPreference",
		func() runtime.Object { return &ReplicaSchedulingPreference{} },
		func() runtime.Object { return &ReplicaSchedulingPreferenceList{} },
	)
	InternalReplicaSchedulingPreferenceStatus = builders.NewInternalResourceStatus(
		"replicaschedulingpreferences",
		"ReplicaSchedulingPreferenceStatus",
		func() runtime.Object { return &ReplicaSchedulingPreference{} },
		func() runtime.Object { return &ReplicaSchedulingPreferenceList{} },
	)
	// Registered resources and subresources
	ApiVersion = builders.NewApiGroup("federatedscheduling.k8s.io").WithKinds(
		InternalReplicaSchedulingPreference,
		InternalReplicaSchedulingPreferenceStatus,
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +genclient
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type ReplicaSchedulingPreference struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   ReplicaSchedulingPreferenceSpec
	Status ReplicaSchedulingPreferenceStatus
}

type ReplicaSchedulingPreferenceSpec struct {
	PreferenceTargetRef ObjectReference
	TotalReplicas       int32
	Rebalance           bool
	Clusters            map[string]ClusterPreferences
}

type ReplicaSchedulingPreferenceStatus struct {
}

type ClusterPreferences struct {
	MinReplicas int64
	MaxReplicas *int64
	Weight      int64
}

type ObjectReference struct {
	Kind string
	Name string
}

//
// ReplicaSchedulingPreference Functions and Structs
//
// +k8s:deepcopy-gen=false
type ReplicaSchedulingPreferenceStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type ReplicaSchedulingPreferenceStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type ReplicaSchedulingPreferenceList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []ReplicaSchedulingPreference
}

func (ReplicaSchedulingPreference) NewStatus() interface{} {
	return ReplicaSchedulingPreferenceStatus{}
}

func (pc *ReplicaSchedulingPreference) GetStatus() interface{} {
	return pc.Status
}

func (pc *ReplicaSchedulingPreference) SetStatus(s interface{}) {
	pc.Status = s.(ReplicaSchedulingPreferenceStatus)
}

func (pc *ReplicaSchedulingPreference) GetSpec() interface{} {
	return pc.Spec
}

func (pc *ReplicaSchedulingPreference) SetSpec(s interface{}) {
	pc.Spec = s.(ReplicaSchedulingPreferenceSpec)
}

func (pc *ReplicaSchedulingPreference) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *ReplicaSchedulingPreference) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc ReplicaSchedulingPreference) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store ReplicaSchedulingPreference.
// +k8s:deepcopy-gen=false
type ReplicaSchedulingPreferenceRegistry interface {
	ListReplicaSchedulingPreferences(ctx request.Context, options *internalversion.ListOptions) (*ReplicaSchedulingPreferenceList, error)
	GetReplicaSchedulingPreference(ctx request.Context, id string, options *metav1.GetOptions) (*ReplicaSchedulingPreference, error)
	CreateReplicaSchedulingPreference(ctx request.Context, id *ReplicaSchedulingPreference) (*ReplicaSchedulingPreference, error)
	UpdateReplicaSchedulingPreference(ctx request.Context, id *ReplicaSchedulingPreference) (*ReplicaSchedulingPreference, error)
	DeleteReplicaSchedulingPreference(ctx request.Context, id string) (bool, error)
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewReplicaSchedulingPreferenceRegistry(sp builders.StandardStorageProvider) ReplicaSchedulingPreferenceRegistry {
	return &storageReplicaSchedulingPreference{sp}
}

// Implement Registry
// storage puts strong typing around storage calls
// +k8s:deepcopy-gen=false
type storageReplicaSchedulingPreference struct {
	builders.StandardStorageProvider
}

func (s *storageReplicaSchedulingPreference) ListReplicaSchedulingPreferences(ctx request.Context, options *internalversion.ListOptions) (*ReplicaSchedulingPreferenceList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	st := s.GetStandardStorage()
	obj, err := st.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*ReplicaSchedulingPreferenceList), err
}

func (s *storageReplicaSchedulingPreference) GetReplicaSchedulingPreference(ctx request.Context, id string, options *metav1.GetOptions) (*ReplicaSchedulingPreference, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*ReplicaSchedulingPreference), nil
}

func (s *storageReplicaSchedulingPreference) CreateReplicaSchedulingPreference(ctx request.Context, object *ReplicaSchedulingPreference) (*ReplicaSchedulingPreference, error) {
	st := s.GetStandardStorage()
	obj, err := st.Create(ctx, object, nil, true)
	if err != nil {
		return nil, err
	}
	return obj.(*ReplicaSchedulingPreference), nil
}

func (s *storageReplicaSchedulingPreference) UpdateReplicaSchedulingPreference(ctx request.Context, object *ReplicaSchedulingPreference) (*ReplicaSchedulingPreference, error) {
	st := s.GetStandardStorage()
	obj, _, err := st.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object), nil, nil)
	if err != nil {
		return nil, err
	}
	return obj.(*ReplicaSchedulingPreference), nil
}

func (s *storageReplicaSchedulingPreference) DeleteReplicaSchedulingPreference(ctx request.Context, id string) (bool, error) {
	st := s.GetStandardStorage()
	_, sync, err := st.Delete(ctx, id, nil)
	return sync, err
}
