/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFederatedIngressPlacements implements FederatedIngressPlacementInterface
type FakeFederatedIngressPlacements struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var federatedingressplacementsResource = schema.GroupVersionResource{Group: "core.federation.k8s.io", Version: "v1alpha1", Resource: "federatedingressplacements"}

var federatedingressplacementsKind = schema.GroupVersionKind{Group: "core.federation.k8s.io", Version: "v1alpha1", Kind: "FederatedIngressPlacement"}

// Get takes name of the federatedIngressPlacement, and returns the corresponding federatedIngressPlacement object, and an error if there is any.
func (c *FakeFederatedIngressPlacements) Get(name string, options v1.GetOptions) (result *v1alpha1.FederatedIngressPlacement, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(federatedingressplacementsResource, c.ns, name), &v1alpha1.FederatedIngressPlacement{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedIngressPlacement), err
}

// List takes label and field selectors, and returns the list of FederatedIngressPlacements that match those selectors.
func (c *FakeFederatedIngressPlacements) List(opts v1.ListOptions) (result *v1alpha1.FederatedIngressPlacementList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(federatedingressplacementsResource, federatedingressplacementsKind, c.ns, opts), &v1alpha1.FederatedIngressPlacementList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FederatedIngressPlacementList{ListMeta: obj.(*v1alpha1.FederatedIngressPlacementList).ListMeta}
	for _, item := range obj.(*v1alpha1.FederatedIngressPlacementList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested federatedIngressPlacements.
func (c *FakeFederatedIngressPlacements) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(federatedingressplacementsResource, c.ns, opts))

}

// Create takes the representation of a federatedIngressPlacement and creates it.  Returns the server's representation of the federatedIngressPlacement, and an error, if there is any.
func (c *FakeFederatedIngressPlacements) Create(federatedIngressPlacement *v1alpha1.FederatedIngressPlacement) (result *v1alpha1.FederatedIngressPlacement, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(federatedingressplacementsResource, c.ns, federatedIngressPlacement), &v1alpha1.FederatedIngressPlacement{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedIngressPlacement), err
}

// Update takes the representation of a federatedIngressPlacement and updates it. Returns the server's representation of the federatedIngressPlacement, and an error, if there is any.
func (c *FakeFederatedIngressPlacements) Update(federatedIngressPlacement *v1alpha1.FederatedIngressPlacement) (result *v1alpha1.FederatedIngressPlacement, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(federatedingressplacementsResource, c.ns, federatedIngressPlacement), &v1alpha1.FederatedIngressPlacement{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedIngressPlacement), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFederatedIngressPlacements) UpdateStatus(federatedIngressPlacement *v1alpha1.FederatedIngressPlacement) (*v1alpha1.FederatedIngressPlacement, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(federatedingressplacementsResource, "status", c.ns, federatedIngressPlacement), &v1alpha1.FederatedIngressPlacement{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedIngressPlacement), err
}

// Delete takes name of the federatedIngressPlacement and deletes it. Returns an error if one occurs.
func (c *FakeFederatedIngressPlacements) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(federatedingressplacementsResource, c.ns, name), &v1alpha1.FederatedIngressPlacement{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFederatedIngressPlacements) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(federatedingressplacementsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.FederatedIngressPlacementList{})
	return err
}

// Patch applies the patch and returns the patched federatedIngressPlacement.
func (c *FakeFederatedIngressPlacements) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FederatedIngressPlacement, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(federatedingressplacementsResource, c.ns, name, data, subresources...), &v1alpha1.FederatedIngressPlacement{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedIngressPlacement), err
}
