apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bars.example.io
spec:
  group: example.io
  version: v1
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          data:
            type: string
        status:
          type: object
  names:
    plural: bars
    singular: bar
    kind: Bar
