apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: bars.example.io
  namespace: federation-system
spec:
  target:
    version: v1
    kind: Bar
  namespaced: true
  propagationEnabled: true
  template:
    group: federation.example.io
    version: v1alpha1
    kind: FederatedBar
  placement:
    kind: FederatedBarPlacement
  override:
    kind: FederatedBarOverride
  overridePath:
  - spec
  - data
