apiVersion: federation.example.io/v1alpha1
kind: FederatedBar
metadata:
  name: test-crd
  namespace: test-namespace
spec:
  template:
    metadata:
      labels:
        app: fed-crd
    spec:
      data: "Hello"
---
apiVersion: federation.example.io/v1alpha1
kind: FederatedBarOverride
metadata:
  name: test-crd
  namespace: test-namespace
spec:
  overrides:
  - clusterName: cluster2
    data: "World"
---
apiVersion: federation.example.io/v1alpha1
kind: FederatedBarPlacement
metadata:
  name: test-crd
  namespace: test-namespace
spec:
  clusterNames:
  - cluster2
  - cluster1
