/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "sigs.k8s.io/federation-v2/pkg/apis/core/v1alpha1"
	scheme "sigs.k8s.io/federation-v2/pkg/client/clientset/versioned/scheme"
)

// FederationConfigsGetter has a method to return a FederationConfigInterface.
// A group's client should implement this interface.
type FederationConfigsGetter interface {
	FederationConfigs(namespace string) FederationConfigInterface
}

// FederationConfigInterface has methods to work with FederationConfig resources.
type FederationConfigInterface interface {
	Create(*v1alpha1.FederationConfig) (*v1alpha1.FederationConfig, error)
	Update(*v1alpha1.FederationConfig) (*v1alpha1.FederationConfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.FederationConfig, error)
	List(opts v1.ListOptions) (*v1alpha1.FederationConfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FederationConfig, err error)
	FederationConfigExpansion
}

// federationConfigs implements FederationConfigInterface
type federationConfigs struct {
	client rest.Interface
	ns     string
}

// newFederationConfigs returns a FederationConfigs
func newFederationConfigs(c *CoreV1alpha1Client, namespace string) *federationConfigs {
	return &federationConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the federationConfig, and returns the corresponding federationConfig object, and an error if there is any.
func (c *federationConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.FederationConfig, err error) {
	result = &v1alpha1.FederationConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("federationconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FederationConfigs that match those selectors.
func (c *federationConfigs) List(opts v1.ListOptions) (result *v1alpha1.FederationConfigList, err error) {
	result = &v1alpha1.FederationConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("federationconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested federationConfigs.
func (c *federationConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("federationconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a federationConfig and creates it.  Returns the server's representation of the federationConfig, and an error, if there is any.
func (c *federationConfigs) Create(federationConfig *v1alpha1.FederationConfig) (result *v1alpha1.FederationConfig, err error) {
	result = &v1alpha1.FederationConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("federationconfigs").
		Body(federationConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a federationConfig and updates it. Returns the server's representation of the federationConfig, and an error, if there is any.
func (c *federationConfigs) Update(federationConfig *v1alpha1.FederationConfig) (result *v1alpha1.FederationConfig, err error) {
	result = &v1alpha1.FederationConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("federationconfigs").
		Name(federationConfig.Name).
		Body(federationConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the federationConfig and deletes it. Returns an error if one occurs.
func (c *federationConfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("federationconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *federationConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("federationconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched federationConfig.
func (c *federationConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FederationConfig, err error) {
	result = &v1alpha1.FederationConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("federationconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
