---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: federation-role
rules:
- apiGroups:
  - core.federation.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - multiclusterdns.federation.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - scheduling.federation.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: federation-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: federation-role
subjects:
- kind: ServiceAccount
  namespace: federation-system
  name: default
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: clusterpropagatedversions.core.federation.k8s.io
spec:
  group: core.federation.k8s.io
  names:
    kind: ClusterPropagatedVersion
    plural: clusterpropagatedversions
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          properties:
            clusterVersions:
              items:
                properties:
                  clusterName:
                    type: string
                  version:
                    type: string
                type: object
              type: array
            overridesVersion:
              type: string
            templateVersion:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: federatedclusters.core.federation.k8s.io
spec:
  group: core.federation.k8s.io
  names:
    kind: FederatedCluster
    plural: federatedclusters
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterRef:
              type: object
            secretRef:
              type: object
            taints:
              items:
                type: object
              type: array
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastProbeTime:
                    format: date-time
                    type: string
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            region:
              type: string
            zone:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: federatedservicestatuses.core.federation.k8s.io
spec:
  group: core.federation.k8s.io
  names:
    kind: FederatedServiceStatus
    plural: federatedservicestatuses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        clusterStatus:
          items:
            properties:
              clusterName:
                type: string
              status:
                type: object
            type: object
          type: array
        kind:
          type: string
        metadata:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: federatedtypeconfigs.core.federation.k8s.io
spec:
  group: core.federation.k8s.io
  names:
    kind: FederatedTypeConfig
    plural: federatedtypeconfigs
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            comparisonField:
              type: string
            enableStatus:
              type: boolean
            namespaced:
              type: boolean
            override:
              properties:
                group:
                  type: string
                kind:
                  type: string
                pluralName:
                  type: string
                version:
                  type: string
              required:
              - kind
              type: object
            placement:
              properties:
                group:
                  type: string
                kind:
                  type: string
                pluralName:
                  type: string
                version:
                  type: string
              required:
              - kind
              type: object
            propagationEnabled:
              type: boolean
            status:
              properties:
                group:
                  type: string
                kind:
                  type: string
                pluralName:
                  type: string
                version:
                  type: string
              required:
              - kind
              type: object
            target:
              properties:
                group:
                  type: string
                kind:
                  type: string
                pluralName:
                  type: string
                version:
                  type: string
              required:
              - kind
              type: object
            template:
              properties:
                group:
                  type: string
                kind:
                  type: string
                pluralName:
                  type: string
                version:
                  type: string
              required:
              - kind
              type: object
          required:
          - target
          - namespaced
          - comparisonField
          - propagationEnabled
          - template
          - placement
          type: object
        status:
          properties:
            observedGeneration:
              format: int64
              type: integer
            propagationController:
              type: string
            statusController:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: propagatedversions.core.federation.k8s.io
spec:
  group: core.federation.k8s.io
  names:
    kind: PropagatedVersion
    plural: propagatedversions
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          properties:
            clusterVersions:
              items:
                properties:
                  clusterName:
                    type: string
                  version:
                    type: string
                type: object
              type: array
            overridesVersion:
              type: string
            templateVersion:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: dnsendpoints.multiclusterdns.federation.k8s.io
spec:
  group: multiclusterdns.federation.k8s.io
  names:
    kind: DNSEndpoint
    plural: dnsendpoints
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            endpoints:
              items:
                properties:
                  dnsName:
                    type: string
                  labels:
                    type: object
                  recordTTL:
                    format: int64
                    type: integer
                  recordType:
                    type: string
                  targets:
                    items:
                      type: string
                    type: array
                type: object
              type: array
          type: object
        status:
          properties:
            observedGeneration:
              format: int64
              type: integer
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: domains.multiclusterdns.federation.k8s.io
spec:
  group: multiclusterdns.federation.k8s.io
  names:
    kind: Domain
    plural: domains
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        domain:
          type: string
        kind:
          type: string
        metadata:
          type: object
        nameServer:
          type: string
      required:
      - domain
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: ingressdnsrecords.multiclusterdns.federation.k8s.io
spec:
  group: multiclusterdns.federation.k8s.io
  names:
    kind: IngressDNSRecord
    plural: ingressdnsrecords
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            hosts:
              items:
                type: string
              type: array
            recordTTL:
              format: int64
              type: integer
          type: object
        status:
          properties:
            dns:
              items:
                properties:
                  cluster:
                    type: string
                  loadBalancer:
                    type: object
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: servicednsrecords.multiclusterdns.federation.k8s.io
spec:
  group: multiclusterdns.federation.k8s.io
  names:
    kind: ServiceDNSRecord
    plural: servicednsrecords
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            allowServiceWithoutEndpoints:
              type: boolean
            dnsPrefix:
              type: string
            domainRef:
              type: string
            externalName:
              type: string
            recordTTL:
              format: int64
              type: integer
          required:
          - domainRef
          type: object
        status:
          properties:
            dns:
              items:
                properties:
                  cluster:
                    type: string
                  loadBalancer:
                    type: object
                  region:
                    type: string
                  zone:
                    type: string
                type: object
              type: array
            domain:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: replicaschedulingpreferences.scheduling.federation.k8s.io
spec:
  group: scheduling.federation.k8s.io
  names:
    kind: ReplicaSchedulingPreference
    plural: replicaschedulingpreferences
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusters:
              type: object
            rebalance:
              type: boolean
            targetKind:
              type: string
            totalReplicas:
              format: int32
              type: integer
          required:
          - targetKind
          - totalReplicas
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    api: federation
    control-plane: controller-manager
    kubebuilder.k8s.io: 1.0.4
  name: federation-controller-manager-service
spec:
  clusterIP: None
  selector:
    api: federation
    control-plane: controller-manager
    kubebuilder.k8s.io: 1.0.4
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    api: federation
    control-plane: controller-manager
    kubebuilder.k8s.io: 1.0.4
  name: federation-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      api: federation
      control-plane: controller-manager
      kubebuilder.k8s.io: 1.0.4
  serviceName: federation-controller-manager-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        api: federation
        control-plane: controller-manager
        kubebuilder.k8s.io: 1.0.4
    spec:
      containers:
      - args:
        - --install-crds=false
        - --federation-namespace=federation-system
        command:
        - /root/controller-manager
        image: quay.io/kubernetes-multicluster/federation-v2:latest
        name: controller-manager
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      terminationGracePeriodSeconds: 10
  updateStrategy: {}
status:
  replicas: 0
