/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FederatedClusterLister helps list FederatedClusters.
type FederatedClusterLister interface {
	// List lists all FederatedClusters in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.FederatedCluster, err error)
	// FederatedClusters returns an object that can list and get FederatedClusters.
	FederatedClusters(namespace string) FederatedClusterNamespaceLister
	FederatedClusterListerExpansion
}

// federatedClusterLister implements the FederatedClusterLister interface.
type federatedClusterLister struct {
	indexer cache.Indexer
}

// NewFederatedClusterLister returns a new FederatedClusterLister.
func NewFederatedClusterLister(indexer cache.Indexer) FederatedClusterLister {
	return &federatedClusterLister{indexer: indexer}
}

// List lists all FederatedClusters in the indexer.
func (s *federatedClusterLister) List(selector labels.Selector) (ret []*v1alpha1.FederatedCluster, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FederatedCluster))
	})
	return ret, err
}

// FederatedClusters returns an object that can list and get FederatedClusters.
func (s *federatedClusterLister) FederatedClusters(namespace string) FederatedClusterNamespaceLister {
	return federatedClusterNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// FederatedClusterNamespaceLister helps list and get FederatedClusters.
type FederatedClusterNamespaceLister interface {
	// List lists all FederatedClusters in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.FederatedCluster, err error)
	// Get retrieves the FederatedCluster from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.FederatedCluster, error)
	FederatedClusterNamespaceListerExpansion
}

// federatedClusterNamespaceLister implements the FederatedClusterNamespaceLister
// interface.
type federatedClusterNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all FederatedClusters in the indexer for a given namespace.
func (s federatedClusterNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.FederatedCluster, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FederatedCluster))
	})
	return ret, err
}

// Get retrieves the FederatedCluster from the indexer for a given namespace and name.
func (s federatedClusterNamespaceLister) Get(name string) (*v1alpha1.FederatedCluster, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("federatedcluster"), name)
	}
	return obj.(*v1alpha1.FederatedCluster), nil
}
