/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FederationConfigLister helps list FederationConfigs.
type FederationConfigLister interface {
	// List lists all FederationConfigs in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.FederationConfig, err error)
	// FederationConfigs returns an object that can list and get FederationConfigs.
	FederationConfigs(namespace string) FederationConfigNamespaceLister
	FederationConfigListerExpansion
}

// federationConfigLister implements the FederationConfigLister interface.
type federationConfigLister struct {
	indexer cache.Indexer
}

// NewFederationConfigLister returns a new FederationConfigLister.
func NewFederationConfigLister(indexer cache.Indexer) FederationConfigLister {
	return &federationConfigLister{indexer: indexer}
}

// List lists all FederationConfigs in the indexer.
func (s *federationConfigLister) List(selector labels.Selector) (ret []*v1alpha1.FederationConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FederationConfig))
	})
	return ret, err
}

// FederationConfigs returns an object that can list and get FederationConfigs.
func (s *federationConfigLister) FederationConfigs(namespace string) FederationConfigNamespaceLister {
	return federationConfigNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// FederationConfigNamespaceLister helps list and get FederationConfigs.
type FederationConfigNamespaceLister interface {
	// List lists all FederationConfigs in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.FederationConfig, err error)
	// Get retrieves the FederationConfig from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.FederationConfig, error)
	FederationConfigNamespaceListerExpansion
}

// federationConfigNamespaceLister implements the FederationConfigNamespaceLister
// interface.
type federationConfigNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all FederationConfigs in the indexer for a given namespace.
func (s federationConfigNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.FederationConfig, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FederationConfig))
	})
	return ret, err
}

// Get retrieves the FederationConfig from the indexer for a given namespace and name.
func (s federationConfigNamespaceLister) Get(name string) (*v1alpha1.FederationConfig, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("federationconfig"), name)
	}
	return obj.(*v1alpha1.FederationConfig), nil
}
