/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubernetes-sigs/federation-v2/pkg/apis/multiclusterdns/v1alpha1"
	scheme "github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IngressDNSRecordsGetter has a method to return a IngressDNSRecordInterface.
// A group's client should implement this interface.
type IngressDNSRecordsGetter interface {
	IngressDNSRecords(namespace string) IngressDNSRecordInterface
}

// IngressDNSRecordInterface has methods to work with IngressDNSRecord resources.
type IngressDNSRecordInterface interface {
	Create(*v1alpha1.IngressDNSRecord) (*v1alpha1.IngressDNSRecord, error)
	Update(*v1alpha1.IngressDNSRecord) (*v1alpha1.IngressDNSRecord, error)
	UpdateStatus(*v1alpha1.IngressDNSRecord) (*v1alpha1.IngressDNSRecord, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.IngressDNSRecord, error)
	List(opts v1.ListOptions) (*v1alpha1.IngressDNSRecordList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IngressDNSRecord, err error)
	IngressDNSRecordExpansion
}

// IngressDNSRecords implements IngressDNSRecordInterface
type IngressDNSRecords struct {
	client rest.Interface
	ns     string
}

// newIngressDNSRecords returns a IngressDNSRecords
func newIngressDNSRecords(c *MulticlusterdnsV1alpha1Client, namespace string) *IngressDNSRecords {
	return &IngressDNSRecords{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the IngressDNSRecord, and returns the corresponding IngressDNSRecord object, and an error if there is any.
func (c *IngressDNSRecords) Get(name string, options v1.GetOptions) (result *v1alpha1.IngressDNSRecord, err error) {
	result = &v1alpha1.IngressDNSRecord{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ingressdnsrecords").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IngressDNSRecords that match those selectors.
func (c *IngressDNSRecords) List(opts v1.ListOptions) (result *v1alpha1.IngressDNSRecordList, err error) {
	result = &v1alpha1.IngressDNSRecordList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ingressdnsrecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested IngressDNSRecords.
func (c *IngressDNSRecords) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ingressdnsrecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a IngressDNSRecord and creates it.  Returns the server's representation of the IngressDNSRecord, and an error, if there is any.
func (c *IngressDNSRecords) Create(IngressDNSRecord *v1alpha1.IngressDNSRecord) (result *v1alpha1.IngressDNSRecord, err error) {
	result = &v1alpha1.IngressDNSRecord{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ingressdnsrecords").
		Body(IngressDNSRecord).
		Do().
		Into(result)
	return
}

// Update takes the representation of a IngressDNSRecord and updates it. Returns the server's representation of the IngressDNSRecord, and an error, if there is any.
func (c *IngressDNSRecords) Update(IngressDNSRecord *v1alpha1.IngressDNSRecord) (result *v1alpha1.IngressDNSRecord, err error) {
	result = &v1alpha1.IngressDNSRecord{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ingressdnsrecords").
		Name(IngressDNSRecord.Name).
		Body(IngressDNSRecord).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *IngressDNSRecords) UpdateStatus(IngressDNSRecord *v1alpha1.IngressDNSRecord) (result *v1alpha1.IngressDNSRecord, err error) {
	result = &v1alpha1.IngressDNSRecord{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ingressdnsrecords").
		Name(IngressDNSRecord.Name).
		SubResource("status").
		Body(IngressDNSRecord).
		Do().
		Into(result)
	return
}

// Delete takes name of the IngressDNSRecord and deletes it. Returns an error if one occurs.
func (c *IngressDNSRecords) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ingressdnsrecords").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *IngressDNSRecords) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ingressdnsrecords").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched IngressDNSRecord.
func (c *IngressDNSRecords) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IngressDNSRecord, err error) {
	result = &v1alpha1.IngressDNSRecord{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ingressdnsrecords").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
