apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: secrets
spec:
  target:
    version: v1
    kind: Secret
  namespaced: true
  comparisonField: ResourceVersion
  propagationEnabled: true
  template:
    group: core.federation.k8s.io
    version: v1alpha1
    kind: FederatedSecret
  placement:
    kind: FederatedSecretPlacement
  override:
    kind: FederatedSecretOverride
  overridePath:
    - data
