apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: serviceaccounts
spec:
  target:
    version: v1
    kind: ServiceAccount
  namespaced: true
  comparisonField: Generation
  propagationEnabled: true
  template:
    group: core.federation.k8s.io
    version: v1alpha1
    kind: FederatedServiceAccount
  placement:
    kind: FederatedServiceAccountPlacement
