apiVersion: types.federation.k8s.io/v1alpha1
kind: FederatedClusterRoleBinding
metadata:
  name: test-clusterrolebinding
spec:
  template:
    subjects:
    - kind: Group
      name: test-user
      apiGroup: rbac.authorization.k8s.io
    roleRef:
      kind: ClusterRole
      name: cluster-admin
      apiGroup: rbac.authorization.k8s.io
  placement:
    clusterNames:
    - cluster2
    - cluster1
