apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedServiceAccount
  metadata:
    name: test-serviceaccount
    namespace: test-namespace
  spec:
    template:
      automountServiceAccountToken: true
