apiVersion: v1
kind: List
items:
- apiVersion: federation.k8s.io/v1alpha1
  kind: FederatedSecretPlacement
  metadata:
    name: test-secret
    namespace: test-namespace
  spec:
    clusternames:
    - cluster2
    - cluster1
