apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedClusterRole
metadata:
  name: test-clusterrole
spec:
  template:
    rules:
    - apiGroups:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
  placement:
    clusterNames:
    - cluster2
    - cluster1
